### PR TITLE
Adding kinase featurizing scripts

### PR DESCRIPTION
**Pull request by jiayeguo**
## Description
Adding kinase featurizing code

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] test distance calculation and compare with Dunbrack results

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by schallerdavid** [comment]
Hey @jiayeguo,
thanks for pushing your code and adapting it to work with MDAnalysis. Do you also have some code to assign structures to the respective Dunbrack clusters? I have the feeling you already have the code to get all necessary information and only a few lines are missing to assign the cluster.

**Comment by jiayeguo** [comment]
Hey @schallerdavid yes you are right. I have the code (and once put it into a jupyter notebook). Now with all the calculated dihedrals and distances, we are just a few lines of code away from Dunbrack clusters. I will have a separate script for that and add that to `kinoml` --- would `features` or `analysis` be a better directory?

**Comment by schallerdavid** [comment]
@jiayeguo,

I think `features` is fine. The most import for now is to get the code into the repo and to show how it works with a notebook. Later we will do the refactoring.

**Comment by schallerdavid** [comment]
@jiayeguo,

I will close this PR for now, since everything from here is in #31. Correct if I am wrong, than we can reopen the PR.

**Pull request closed without merging**
