### PR TITLE
Fix warnings during building docs

### PR DESCRIPTION
**Pull request by schallerdavid**
## Description
This PR aims to fix all warnings when building docs by the CI

## Todos
  - [x] fix all warnings
  - [x] Add docs badge -> docs|passing

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by schallerdavid** [comment]
@t-kimber docs are passing 🎉 

However, I can't really figure out how to add a badge for this particular job of the ci run. Do you have an easy solution?

**Comment by schallerdavid** [comment]
I found a solution by just splitting the docs into a separate workflow.

**Review by t-kimber — APPROVED** [review]
Wonderful !! Let's merge!

**Comment by jchodera** [comment]
Woohoo!

**Pull request merged**
